[package]
name = "computable"
version = "0.1.0"
edition = "2024"

[dependencies]
crossbeam-channel = "0.5"
num-bigint = "0.4"
num-integer = "0.1"
num-traits = "0.2"
parking_lot = "0.12"
rayon = "1.10"
rand = "0.8"

[features]
benchmarks = []

[[bin]]
name = "benchmarks"
path = "benchmarks/benchmarks.rs"
required-features = ["benchmarks"]

[[bin]]
name = "profile"
path = "benchmarks/profile.rs"
required-features = ["benchmarks"]

[[bin]]
name = "profile_refinement"
path = "benchmarks/profile_refinement.rs"
required-features = ["benchmarks"]

[[bin]]
name = "profile_detailed"
path = "benchmarks/profile_detailed.rs"
required-features = ["benchmarks"]

[[bin]]
name = "profile_threadpool"
path = "benchmarks/profile_threadpool.rs"
required-features = ["benchmarks"]
